# SPDX-FileCopyrightText: 2025 ANSSI
# SPDX-License-Identifier: BSD-2-Clause

[Distribution]
Distribution=fedora
# TODO: upgrade to Fedora 41 or 42 once a workaround is found for missing efitools package.
Release=40

[Validation]
SecureBoot=true
SecureBootKey=mkosi.extra/var/lib/sbctl/keys/db/db.key
SecureBootCertificate=mkosi.extra/var/lib/sbctl/keys/db/db.pem
Checksum=true

[Config]
MinimumVersion=24

[Output]
Format=disk
ImageId=chipsec_check
# Necessary to make Windows recognize the FAT32 partition on external media (USB stick)
SectorSize=512

[Content]
Bootable=true
Bootloader=systemd-boot
Hostname=chispec

# Packages required for a bootable image
# https://github.com/systemd/mkosi/blob/main/docs/bootable.md
Packages=kernel
         systemd
         systemd-boot
         grub2-pc
         shim-x64
         udev
         util-linux
# Network
         systemd-networkd
         systemd-resolved
         iproute
# Other packages to run chipsec-check tests
         cpuid
         cryptsetup
         dbxtool
         diffutils
         dmidecode
         dnf
         edk2-ovmf
         e2fsprogs
         fwts
         fwupd
         git
         kbd
         kernel-devel
         lshw
         msr-tools
         openssl
         pciutils
         python3
         python3-pip
         rizin
         sbsigntools
         strace
         tpm2-tools
         tpm2-tss
# fwupd relies on this but doesn't set the dependency
         udisks2
         usbutils
         vim

BuildPackages=
         rustup
         autoconf
         automake
         bison
         cmake
         dkms
         dtc
         elfutils-libelf-devel
         flex
         flex-devel
         gcc
         gcc-c++
         git
         glib2
         glib2-devel
         glibc-static
         golang
         kernel
         kernel-devel
         kernel-headers
         libbsd-devel
         libfdt
         libfdt-devel
         libstdc++-static
         libtool
         make
         nasm
         pciutils
         pciutils-devel
         pcre-devel
         pcre2
         pcre2-devel
         pcre2-utf16
         pcre2-utf32
         python-virtualenv
         python3-devel
         python3-setuptools
         python3-wheel
         redhat-rpm-config
         unzip
         zlib-devel

Autologin=true
KernelCommandLine=iommu=force intel_iommu=on amd_iommu=on

[Build]
WithNetwork=false
BuildSourcesEphemeral=true
ToolsTree=default
