[Partition]
# Microsoft Basic Data Partition, so that it can be read by Windows as well
# https://en.wikipedia.org/wiki/Microsoft_basic_data_partition
Type=EBD0A0A2-B9E5-4433-87C0-68B6B72699C7
Format=vfat
# We use this label in /etc/fstab to mount the partition on /srv
# We do *not* use Type=srv because it is not recognized by Windows (eventhough it would automount on Linux through systemd-auto-gpt-generator)
Label=SRV
SizeMinBytes=1G
SizeMaxBytes=1G
